# Chargement des données et des modules

In [1]:
# Chargement des librairies
import pandas as pd
import numpy as np

# Affichage propre des graphiques
%matplotlib inline

In [2]:
# Chargement des données
disasters = pd.read_csv("data/disasters_1900_2021.csv")
conflicts = pd.read_csv("data/conflicts.csv")
indicator_info = pd.read_csv("data/indicator_info.csv") # Ce dataset ne servira que d'un simple document supplémentaire pour comprendre les indicateurs dans le jeu de donnée Demographics
life_expectancy = pd.read_csv("data/demographic.csv", low_memory=False)
health_inequality = pd.read_excel("data/health_inequality.xlsx")

In [3]:
# Apercu du jeu de donnée Natural Disasters
disasters.head(5)

,Year,Seq,Glide,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Disaster Subsubtype,Event Name,Country,...,No Affected,No Homeless,Total Affected,Insured Damages ('000 US$),Total Damages ('000 US$),CPI,Adm Level,Admin1 Code,Admin2 Code,Geo Locations
0,1900,9002,NaN,Natural,Climatological,Drought,Drought,NaN,NaN,Cabo Verde,...,NaN,NaN,NaN,NaN,NaN,3.221647,NaN,NaN,NaN,NaN
1,1900,9001,NaN,Natural,Climatological,Drought,Drought,NaN,NaN,India,...,NaN,NaN,NaN,NaN,NaN,3.221647,NaN,NaN,NaN,NaN
2,1902,12,NaN,Natural,Geophysical,Earthquake,Ground movement,NaN,NaN,Guatemala,...,NaN,NaN,NaN,NaN,25000.0,3.350513,NaN,NaN,NaN,NaN
3,1902,3,NaN,Natural,Geophysical,Volcanic activity,Ash fall,NaN,Santa Maria,Guatemala,...,NaN,NaN,NaN,NaN,NaN,3.350513,NaN,NaN,NaN,NaN
4,1902,10,NaN,Natural,Geophysical,Volcanic activity,Ash fall,NaN,Santa Maria,Guatemala,...,NaN,NaN,NaN,NaN,NaN,3.350513,NaN,NaN,NaN,NaN

In [4]:
# Apercu du jeu de donnée Conflicts
conflicts.head(5)

,conflict_id,location,side_a,side_a_id,side_a_2nd,side_b,side_b_id,side_b_2nd,incompatibility,territory_name,...,ep_end,ep_end_date,ep_end_prec,gwno_a,gwno_a_2nd,gwno_b,gwno_b_2nd,gwno_loc,region,version
0,11342,India,Government of India,141,NaN,GNLA,1163,NaN,1,Garoland,...,1,2012-12-21,NaN,750,NaN,NaN,NaN,750,3,25.1
1,11342,India,Government of India,141,NaN,GNLA,1163,NaN,1,Garoland,...,1,2014-11-27,NaN,750,NaN,NaN,NaN,750,3,25.1
2,11343,"Egypt, Israel",Government of Egypt,117,NaN,Government of Israel,121,NaN,1,Suez/Sinai,...,1,1967-06-10,NaN,651,NaN,666,NaN,"651, 666",2,25.1
3,11343,"Egypt, Israel",Government of Egypt,117,NaN,Government of Israel,121,NaN,1,Suez/Sinai,...,0,NaN,NaN,651,NaN,666,NaN,"651, 666",2,25.1
4,11343,"Egypt, Israel",Government of Egypt,117,NaN,Government of Israel,121,NaN,1,Suez/Sinai,...,1,1970-08-07,NaN,651,NaN,666,NaN,"651, 666",2,25.1

In [5]:
# Apercu du jeu de donnée Info Supplémentaire
indicator_info.head(5)

,IndicatorNo,Topic,Indicator,IndicatorName,Unit
0,1,Population,TPopulation1Jan,"Total Population, as of 1 January",thousands
1,2,Population,TPopulation1July,"Total Population, as of 1 July",thousands
2,3,Population,TPopulationMale1July,"Male Population, as of 1 July",thousands
3,4,Population,TPopulationFemale1July,"Female Population, as of 1 July",thousands
4,5,Population,PopDensity,"Population Density, as of 1 July",persons per square km

In [6]:
# Apercu du jeu de donnée Demographic
life_expectancy.head(5)

,SortOrder,LocID,Notes,ISO3_code,ISO2_code,SDMX_code,LocTypeID,LocTypeName,ParentID,Location,...,Q0060Male,Q0060Female,Q1550,Q1550Male,Q1550Female,Q1560,Q1560Male,Q1560Female,NetMigrations,CNMR
0,NaN,5507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADB region: Central and West Asia,...,654.5798,631.8067,297.6529,298.4483,297.2079,443.3215,457.3384,427.3167,201.196,2.907
1,NaN,5507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADB region: Central and West Asia,...,642.5944,619.1788,292.4375,293.1236,292.0887,436.9979,451.4368,420.7398,195.070,2.760
2,NaN,5507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADB region: Central and West Asia,...,630.8166,607.6061,286.6916,287.3395,286.3341,429.8298,444.5151,413.5565,182.671,2.529
3,NaN,5507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADB region: Central and West Asia,...,619.9937,596.2667,281.4671,282.0251,281.1446,423.2008,438.1189,406.9265,164.189,2.222
4,NaN,5507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADB region: Central and West Asia,...,610.3878,586.3428,276.8312,277.5799,276.2557,417.3453,432.7454,400.7629,163.064,2.157

In [7]:
health_inequality.head(5)

,setting,date,source,indicator_abbr,indicator_name,dimension,subgroup,estimate,se,ci_lb,...,iso3,favourable_indicator,indicator_scale,ordered_dimension,subgroup_order,reference_subgroup,whoreg6,wbincome2025,update,dataset_id
0,Afghanistan,1957,WHO Global Health Observatory,MDG_0000000001,Infant mortality rate (deaths per 1000 live bi...,Sex,Female,247.968162,NaN,194.625473,...,AFG,0,1000,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho
1,Afghanistan,1957,WHO Global Health Observatory,MDG_0000000001,Infant mortality rate (deaths per 1000 live bi...,Sex,Male,272.898981,NaN,214.032553,...,AFG,0,1000,0,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho
2,Afghanistan,1957,WHO Global Health Observatory,MDG_0000000007,Under-five mortality rate (model-based estimat...,Sex,Female,363.074361,NaN,286.019402,...,AFG,0,1000,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho
3,Afghanistan,1957,WHO Global Health Observatory,MDG_0000000007,Under-five mortality rate (model-based estimat...,Sex,Male,379.310303,NaN,297.924681,...,AFG,0,1000,0,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho
4,Afghanistan,1958,WHO Global Health Observatory,MDG_0000000001,Infant mortality rate (deaths per 1000 live bi...,Sex,Female,245.144576,NaN,197.317972,...,AFG,0,1000,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho

# Nettoyage des données

## Pour le jeu de donnée "Natural Disasters"

### Ajout des filtres pour les intervalles de dates

### Sélection des colonnes utiles

In [8]:
disasters = disasters[['Year', 'Country', 'Disaster Type', 'Total Deaths', 'Total Affected']]

In [9]:
disasters.head(5)

   Year     Country      Disaster Type  Total Deaths  Total Affected
0  1900  Cabo Verde            Drought       11000.0             NaN
1  1900       India            Drought     1250000.0             NaN
2  1902   Guatemala         Earthquake        2000.0             NaN
3  1902   Guatemala  Volcanic activity        1000.0             NaN
4  1902   Guatemala  Volcanic activity        6000.0             NaN

### Renommage des colonnes

In [10]:
# Afin d'enlever les espaces 
disasters = disasters.rename(columns={
    'Year': 'Year',
    'Country': 'Country',
    'Disaster Type': 'Disaster_type',
    'Total Deaths': 'Total_deaths',
    'Total Affected': 'Total_affected'
})

### Filtrage de 1950-2021

In [11]:
disasters = disasters[disasters['Year'].between(1950,2021)]

### Gestion des valeurs manquantes

La valeur manquante dans le jeu de donnée peut autant signifier qu'il n'y a **pas eu de morts** dans le cas de la colonne **Total Deaths** ou que la donnée soit vraiment **manquante**.

In [12]:
# Regardons le nombre de valeurs manquantes de la colonne Total Deaths par type de catastrophe naturelle
print(disasters.groupby('Disaster_type')['Total_deaths'].apply(
    lambda x: x.isnull().sum()
).sort_values(ascending=False))

Disaster_type
Flood                    1507
Storm                    1156
Drought                   679
Earthquake                366
Wildfire                  270
Epidemic                  228
Volcanic activity         171
Extreme temperature       113
Insect infestation         93
Landslide                  35
Mass movement (dry)         2
Impact                      1
Animal accident             0
Fog                         0
Glacial lake outburst       0
Name: Total_deaths, dtype: int64

On remarque que les valeurs manquantes sont concentrées sur les 3 catastrophes naturelles: **inondation, tempête, sécheresse**. Ce qui est logique étant donné que ce sont les catastrophes naturelles **les moins mortelles** pour la population. Donc, les valeurs manquantes ici représentent réellement une donnée. Pour les comptabiliser, on va les remplacer par 0.

In [13]:
# Remplir les valeurs manquantes par 0
disasters['Total_deaths'] = disasters['Total_deaths'].fillna(0)
disasters['Total_affected'] = disasters['Total_affected'].fillna(0)

# Imputation par la médiane par type de catastrophe
columns = ['Total_deaths', 'Total_affected']

for col in columns:
    disasters[col] = disasters.groupby('Country')[col].transform(
        lambda x: x.fillna(x.median())
    )
    disasters[col] = disasters[col].fillna(disasters[col].median())

In [14]:
# Aggrégation par année et par pays
disasters_agg = disasters.groupby(['Country', 'Year']).agg(
    nb_disasters     = ('Disaster_type', 'count'),
    total_deaths_per_country = ('Total_deaths', 'sum'),
    total_affected   = ('Total_affected', 'sum')
).reset_index()

In [15]:
disasters_agg.head(5)

       Country  Year  nb_disasters  total_deaths_per_country  total_affected
0  Afghanistan  1954             1                    2000.0             0.0
1  Afghanistan  1956             2                     151.0          2000.0
2  Afghanistan  1963             1                     107.0             0.0
3  Afghanistan  1969             1                       0.0         48000.0
4  Afghanistan  1971             2                     100.0             0.0

## Pour le jeux de donnée "Conflicts"

### Renommage des colonnes

1 = Conflit mineur : entre 25 et 999 morts au combat au cours d'une année donnée. 2 = Guerre : au moins 1 000 morts au combat au cours d'une année donnée.

1 = extrasystémique (entre un État et un groupe non étatique situé hors de son propre territoire, où la partie gouvernementale lutte pour conserver le contrôle d'un territoire situé en dehors du système étatique) 2 = interétatique (les deux parties sont des États dans le système de classification de Gleditsch et Ward) 3 = intra-étatique (la partie A est toujours un gouvernement ; la partie B est toujours un ou plusieurs groupes rebelles ; il n'y a pas d'implication de gouvernements étrangers avec des troupes, c'est-à-dire qu'il n'y a pas de code side_a_2nd ou side_b_2nd) 4 = intra-étatique internationalisé (le camp A est toujours un gouvernement ; le camp B est toujours un ou plusieurs groupes rebelles ; il y a implication de gouvernements étrangers avec des troupes, c'est-à-dire qu'il y a au moins UN code side_a_2nd ou side_b_2nd)

In [16]:
conflicts = conflicts.rename(columns={
    'year' : 'year',
    'location': 'Country'
})

### Filtrage pour l'année 1950 jusqu'à 2021

In [17]:
conflicts =conflicts[conflicts['year'].between(1950, 2021)]

### Sélection des colonnes essentielles

In [18]:
conflicts =conflicts[['Country', 'year', 'intensity_level', 'type_of_conflict']]

In [19]:
conflicts.head(5)

         Country  year  intensity_level  type_of_conflict
0          India  2012                1                 3
1          India  2014                1                 3
2  Egypt, Israel  1967                2                 2
3  Egypt, Israel  1969                1                 2
4  Egypt, Israel  1970                1                 2

## Pour le jeu de donnée "Demographics"

### Sélection des colonnes nécessaires

In [20]:
life_expectancy = life_expectancy[['Location', 'Time', 'LEx', 'LExMale', 'LExFemale', 'Deaths','DeathsMale', 'DeathsFemale', 'IMR', 'PopGrowthRate', 'InfantDeaths', 'Under5Deaths']]

### Renommage des colonnes

In [21]:
life_expectancy = life_expectancy.rename(columns={
    'Location': 'Country',
    'Time': 'Year',
    'LEx': 'Life_expectancy',
    'LExMale': 'Life_expectancy_male',
    'LExFemale': 'Life_expectancy_female',
    'IMR': 'Infant_mortality_rate'
})

### Filtrage des années

In [22]:
life_expectancy = life_expectancy[life_expectancy['Year'].between(1950,2021)]

In [23]:
life_expectancy.head(5)

,Country,Year,Life_expectancy,Life_expectancy_male,Life_expectancy_female,Deaths,DeathsMale,DeathsFemale,Infant_mortality_rate,PopGrowthRate,InfantDeaths,Under5Deaths
0,ADB region: Central and West Asia,1950,38.6085,38.1082,39.1261,1710.506,896.754,813.752,207.0834,2.058,600.102,930.552
1,ADB region: Central and West Asia,1951,39.6435,39.1333,40.1776,1693.605,888.959,804.646,200.9781,2.143,600.824,910.110
2,ADB region: Central and West Asia,1952,40.5673,40.0791,41.0807,1685.112,884.170,800.942,196.0193,2.212,602.648,898.759
3,ADB region: Central and West Asia,1953,41.4405,40.9378,41.9706,1679.966,882.165,797.801,190.7597,2.271,603.859,889.725
4,ADB region: Central and West Asia,1954,42.2044,41.7062,42.7313,1680.927,882.632,798.295,185.8880,2.342,605.992,885.494

## Pour le jeu de donnée "Health Inequality"

### Filtrage pour l'année 1950 jusqu'à 2021

In [24]:
health_inequality.tail(5)

,setting,date,source,indicator_abbr,indicator_name,dimension,subgroup,estimate,se,ci_lb,...,iso3,favourable_indicator,indicator_scale,ordered_dimension,subgroup_order,reference_subgroup,whoreg6,wbincome2025,update,dataset_id
917758,occupied Palestinian territory,2023,WHO Global Health Observatory,NUTSTUNTINGPREV,Stunting prevalence among children aged <5 yea...,Sex,Male,8.2,NaN,7.0,...,PSE,0,100,0,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho
917759,occupied Palestinian territory,2024,WHO Global Health Observatory,NUTOVERWEIGHTPREV,Overweight prevalence among children aged <5 y...,Sex,Female,8.2,NaN,5.4,...,PSE,0,100,0,0,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho
917760,occupied Palestinian territory,2024,WHO Global Health Observatory,NUTOVERWEIGHTPREV,Overweight prevalence among children aged <5 y...,Sex,Male,9.4,NaN,6.2,...,PSE,0,100,0,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho
917761,occupied Palestinian territory,2024,WHO Global Health Observatory,NUTSTUNTINGPREV,Stunting prevalence among children aged <5 yea...,Sex,Female,7.6,NaN,6.4,...,PSE,0,100,0,0,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho
917762,occupied Palestinian territory,2024,WHO Global Health Observatory,NUTSTUNTINGPREV,Stunting prevalence among children aged <5 yea...,Sex,Male,8.4,NaN,7.1,...,PSE,0,100,0,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho

In [25]:
health_inequality = health_inequality[health_inequality['date'].between(1950,2021)]

In [26]:
health_inequality.tail(5)

,setting,date,source,indicator_abbr,indicator_name,dimension,subgroup,estimate,se,ci_lb,...,iso3,favourable_indicator,indicator_scale,ordered_dimension,subgroup_order,reference_subgroup,whoreg6,wbincome2025,update,dataset_id
917662,occupied Palestinian territory,2021,WHO Global Health Observatory,WSH_SANITATION_SAFELY_MANAGED,Population using safely managed sanitation ser...,Place of residence,Urban,73.45498,NaN,NaN,...,PSE,1,100,0,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho
917663,occupied Palestinian territory,2021,WHO Global Health Observatory,WSH_WATER_BASIC,Population using at least basic drinking-water...,Place of residence,Rural,99.38697,NaN,NaN,...,PSE,1,100,0,0,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho
917664,occupied Palestinian territory,2021,WHO Global Health Observatory,WSH_WATER_BASIC,Population using at least basic drinking-water...,Place of residence,Urban,97.80785,NaN,NaN,...,PSE,1,100,0,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho
917665,occupied Palestinian territory,2021,WHO Global Health Observatory,WSH_WATER_SAFELY_MANAGED,Population using safely managed drinking-water...,Place of residence,Rural,76.03888,NaN,NaN,...,PSE,1,100,0,0,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho
917666,occupied Palestinian territory,2021,WHO Global Health Observatory,WSH_WATER_SAFELY_MANAGED,Population using safely managed drinking-water...,Place of residence,Urban,81.21311,NaN,NaN,...,PSE,1,100,0,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho

Les dates ont bien été filtrées.

### Sélection des colonnes nécessaires

In [27]:
print(health_inequality.columns)

Index(['setting', 'date', 'source', 'indicator_abbr', 'indicator_name',
       'dimension', 'subgroup', 'estimate', 'se', 'ci_lb', 'ci_ub',
       'population', 'flag', 'setting_average', 'iso3', 'favourable_indicator',
       'indicator_scale', 'ordered_dimension', 'subgroup_order',
       'reference_subgroup', 'whoreg6', 'wbincome2025', 'update',
       'dataset_id'],
      dtype='str')

Toutes les colonnes semblent nécessaires, aucune séléction ne sera faites pour ce dataset.

### Visionnage des catégories dans les colonnes

In [28]:
print("setting :")
print(health_inequality["setting"].unique())
print("\n")

print("indicator_name :")
print(health_inequality["indicator_name"].unique())
print("\n")

print("subgroup :")
print(health_inequality["subgroup"].unique())
print("\n")

print("whoreg6 :")
print(health_inequality["whoreg6"].unique())

setting :
<StringArray>
[                       'Afghanistan',                            'Albania',
                            'Algeria',                            'Andorra',
                             'Angola',                'Antigua and Barbuda',
                          'Argentina',                            'Armenia',
                          'Australia',                            'Austria',
 ...
           'United States of America',                            'Uruguay',
                         'Uzbekistan',                            'Vanuatu',
 'Venezuela (Bolivarian Republic of)',                           'Viet Nam',
                              'Yemen',                             'Zambia',
                           'Zimbabwe',     'occupied Palestinian territory']
Length: 198, dtype: str


indicator_name :
<StringArray>
[                                                     'Infant mortality rate (deaths per 1000 live births)',
                          'Under-five mortality rate (model-based estimates) (deaths per 1000 live births)',
                                      'Cholesterol, mean high-density lipoprotein (HDL) (age-standardized)',
                                                 'Cholesterol, mean high-density lipoprotein (HDL) (crude)',
                              'Cholesterol, mean non-high-density lipoprotein (non-HDL) (age-standardized)',
                                         'Cholesterol, mean non-high-density lipoprotein (non-HDL) (crude)',
                                                               'Cholesterol, mean total (age-standardized)',
                                                                          'Cholesterol, mean total (crude)',
            'Hypertension: raised blood pressure (SBP>=140 OR DBP>=90) among adults aged 30-79 (crude) (%)',
 'Hypertension: raised blood pressure (SBP>=140 OR DBP>=90) among adults aged 30-79 (age-standardized) (%)',
 ...
                                      'Effective cataract surgical coverage of adults aged 50 and over (%)',
                         'Assistive technology: Travel distance to obtain assistive products (%) - 100+ km',
                        'Assistive technology: Travel distance to obtain assistive products (%) - 26-50 km',
                       'Assistive technology: Travel distance to obtain assistive products (%) - 51-100 km',
                         'Assistive technology: Travel distance to obtain assistive products (%) - 6-25 km',
                           'Assistive technology: Travel distance to obtain assistive products (%) - <6 km',
                                                 'Assistive technology: Met need of assistive products (%)',
                                                     'Assistive technology: Need of assistive products (%)',
                                                      'Assistive technology: Use of assistive products (%)',
                                   'Alcohol-attributable DALYs (age-standardized) (per 100 000 population)']
Length: 178, dtype: str


subgroup :
<StringArray>
[                                            'Female',
                                               'Male',
                                        '10-19 years',
                                          '5-9 years',
                                              'Rural',
                                              'Urban',
                                        '10-14 years',
                                        '15-19 years',
                          'Adults only (20-59 years)',
               'Adults with children and adolescents',
 'Multigenerational and/or adults with older persons',
                       'Multigenerational households',
                          'Adults with older persons',
                     'Only older adults (>=60 years)',
                               'Quintile 1 (poorest)',
                                         'Quintile 2',
                                         'Quintile 3',
                                         'Quintile 4',
                               'Quintile 5 (richest)',
                                        '15-24 years',
                                        '25-34 years',
                                        '35-44 years',
                                        '45-54 years',
                                        '55-64 years',
                                        '65-74 years',
                                        '75-84 years',
                                          '85+ years',
          'Only adolescents and children (<20 years)',
                                          '0-4 years',
                                        '18-29 years',
                                        '30-39 years',
                                        '40-49 years',
                                         '5-17 years',
                                        '50-59 years',
                                        '60-69 years',
                                        '70-79 years',
                                          '80+ years']
Length: 37, dtype: str


whoreg6 :
<StringArray>
['Eastern Mediterranean',              'European',               'African',
              'Americas',       'Western Pacific',       'South-East Asia',
                     nan]
Length: 7, dtype: str

### Renommage des colonnes

In [29]:
health_inequality = health_inequality.rename(columns={
    "setting": "country",
    "date": "date",
    "indicator_abbr": "indicator_abbr",
    "indicator_name": "indicator_name",
    "subgroup": "group",
    "estimate": "value",
    "iso3": "country_code",
    "whoreg6": "region",
    "wbincome2025": "income_level",
    "ci_lb": "ci_lower",
    "ci_ub": "ci_upper",
})

In [30]:
health_inequality.head(5)

,country,date,source,indicator_abbr,indicator_name,dimension,group,value,se,ci_lower,...,country_code,favourable_indicator,indicator_scale,ordered_dimension,subgroup_order,reference_subgroup,region,income_level,update,dataset_id
0,Afghanistan,1957,WHO Global Health Observatory,MDG_0000000001,Infant mortality rate (deaths per 1000 live bi...,Sex,Female,247.968162,NaN,194.625473,...,AFG,0,1000,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho
1,Afghanistan,1957,WHO Global Health Observatory,MDG_0000000001,Infant mortality rate (deaths per 1000 live bi...,Sex,Male,272.898981,NaN,214.032553,...,AFG,0,1000,0,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho
2,Afghanistan,1957,WHO Global Health Observatory,MDG_0000000007,Under-five mortality rate (model-based estimat...,Sex,Female,363.074361,NaN,286.019402,...,AFG,0,1000,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho
3,Afghanistan,1957,WHO Global Health Observatory,MDG_0000000007,Under-five mortality rate (model-based estimat...,Sex,Male,379.310303,NaN,297.924681,...,AFG,0,1000,0,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho
4,Afghanistan,1958,WHO Global Health Observatory,MDG_0000000001,Infant mortality rate (deaths per 1000 live bi...,Sex,Female,245.144576,NaN,197.317972,...,AFG,0,1000,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho

## Fractionnement ou fusion des colonnes

### Fractionnement de la colonnes "indicator_name"

Afin de faciliter le futur traitement des données, la grille de lecture de dataset se doit d'être la plus lisible possible, ce qui facilitera le maniement des données.
Evidemment, lorsqu'on fait des simplifications, il est plus prudent de créer des colonnes supplémentaires que d'écraser les anciennes (plus riches d'information).

Comme nous l'avons vu dans la catégorie "Visionnage des colonnes", le dataset est très complet. Il couvre nos besoins et plus encore.

Nous avons bien trop de catégories pour les thèmes suivants :
- l'âge
- le cholesterole 
- et enfin, la distance pour obtenir une aide technique (assistive techology)

### Simplification de l'âge

Voici les catégories d'âge disponsible :
- 10-19 years,
- 5-9 years,
- 10-14 years,
- 15-19 years,
- 15-24 years,
- 25-34 years,
- 35-44 years,
- 45-54 years,
- 55-64 years,
- 65-74 years,
- 75-84 years,
- 85+ years,
- 0-4 years,
- 18-29 years,
- 30-39 years,
- 40-49 years,
- 5-17 years,
- 50-59 years,
- 60-69 years,
- 70-79 years,
- et enfin 80+ years.

Nous allons les simplifier en 3 catégories principales :
- les -25 ans
- les -60 ans
- et les +60 ans

In [31]:
def age_group(x):
    if pd.isna(x):
        return np.nan

    if x in [
        "0-4 years",
        "5-9 years",
        "10-14 years",
        "5-17 years",
        "15-19 years",
        "10-19 years",
        "15-19 years",
        "15-24 years"
    ]:
        return "-25"

    elif x in [
        "18-29 years",
        "25-34 years",
        "30-39 years",
        "35-44 years",
        "45-54 years",
        "50-59 years"
    ]:
        return "-60"

    elif x in [
        "55-64 years",
        "60-69 years",
        "65-74 years",
        "70-79 years",
        "75-84 years",
        "80+ years",
        "85+ years",
        "Only older adults (>=60 years)"
    ]:
        return "60+"

    return np.nan

health_inequality["age"] = health_inequality["group"].apply(age_group)

In [32]:
health_inequality.iloc[376:381] # choix de ligne qui présente la catégorie "cholesterole" afin de vérifier si tout fonctionne

,country,date,source,indicator_abbr,indicator_name,dimension,group,value,se,ci_lower,...,favourable_indicator,indicator_scale,ordered_dimension,subgroup_order,reference_subgroup,region,income_level,update,dataset_id,age
376,Afghanistan,1991,WHO Global Health Observatory,NCD_BMI_PLUS2C_SEX_MLE,Obesity prevalence among school-age children a...,Age (2 groups) (5-19),10-19 years,0.805040,NaN,0.095334,...,0,100,0,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,-25
377,Afghanistan,1991,WHO Global Health Observatory,NCD_BMI_PLUS2C_SEX_MLE,Obesity prevalence among school-age children a...,Age (2 groups) (5-19),5-9 years,0.997518,NaN,0.053112,...,0,100,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,-25
378,Afghanistan,1991,WHO Global Health Observatory,NCD_CHOL_MEANHDL_A,"Cholesterol, mean high-density lipoprotein (HD...",Sex,Female,1.100000,NaN,0.900000,...,0,100,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN
379,Afghanistan,1991,WHO Global Health Observatory,NCD_CHOL_MEANHDL_A,"Cholesterol, mean high-density lipoprotein (HD...",Sex,Male,1.200000,NaN,0.900000,...,0,100,0,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN
380,Afghanistan,1991,WHO Global Health Observatory,NCD_CHOL_MEANHDL_C,"Cholesterol, mean high-density lipoprotein (HD...",Sex,Female,1.100000,NaN,0.900000,...,0,100,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN

Si on regarde la dernière colonne, on voit bien que l'âge a été ajouté (de manière simplifiée)

### Simplification des données sur le cholesterole

Voici les données disponibles sur le cholestérole :
- Cholesterol, mean high-density lipoprotein (HDL) (age-standardized),
- Cholesterol, mean high-density lipoprotein (HDL) (crude),
- Cholesterol, mean non-high-density lipoprotein (non-HDL) (age-standardized),
- Cholesterol, mean non-high-density lipoprotein (non-HDL) (crude),
- Cholesterol, mean total (age-standardized),
et enfi, Cholesterol, mean total (crude).

Ici nous avons fait le choix de garder uniquement les mesures standardisées en fonction de l'âge et du pays.
Ce sont les mesures les plus fiables à utiliser lors de comparaison internationales.

On va donc garder :
- Cholesterol, mean high-density lipoprotein (HDL) (age-standardized),
- Cholesterol, mean non-high-density lipoprotein (non-HDL) (age-standardized),
- et Cholesterol, mean total (age-standardized)

Qui seront respectivement renommé :
- good
- bad
- total

In [33]:
def cholesterol_simplification(x):
    if pd.isna(x):
        return np.nan

    if x in ["Cholesterol, mean high-density lipoprotein (HDL) (age-standardized)"]:
        return "good"
    
    if x in ["Cholesterol, mean non-high-density lipoprotein (non-HDL) (age-standardized)"]:
        return "bad"
    
    if x in ["Cholesterol, mean total (age-standardized)"]:
        return "total"
    
health_inequality["cholesterol"] = health_inequality["indicator_name"].apply(cholesterol_simplification)

Vérifions tout de même que nous avons assez de données :

In [34]:
health_inequality["cholesterol"].value_counts()

cholesterol
good     14898
bad      14898
total    14898
Name: count, dtype: int64

In [35]:
health_inequality.iloc[1206:1217] # choix de ligne qui présente la catégorie "cholesterol" afin de vérifier si tout fonctionne

,country,date,source,indicator_abbr,indicator_name,dimension,group,value,se,ci_lower,...,indicator_scale,ordered_dimension,subgroup_order,reference_subgroup,region,income_level,update,dataset_id,age,cholesterol
1206,Afghanistan,2000,WHO Global Health Observatory,NCD_CHOL_MEANHDL_C,"Cholesterol, mean high-density lipoprotein (HD...",Sex,Female,1.100000,NaN,0.900000,...,100,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN
1207,Afghanistan,2000,WHO Global Health Observatory,NCD_CHOL_MEANHDL_C,"Cholesterol, mean high-density lipoprotein (HD...",Sex,Male,1.100000,NaN,0.900000,...,100,0,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN
1208,Afghanistan,2000,WHO Global Health Observatory,NCD_CHOL_MEANNONHDL_A,"Cholesterol, mean non-high-density lipoprotein...",Sex,Female,3.200000,NaN,2.900000,...,100,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,bad
1209,Afghanistan,2000,WHO Global Health Observatory,NCD_CHOL_MEANNONHDL_A,"Cholesterol, mean non-high-density lipoprotein...",Sex,Male,3.100000,NaN,2.800000,...,100,0,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,bad
1210,Afghanistan,2000,WHO Global Health Observatory,NCD_CHOL_MEANNONHDL_C,"Cholesterol, mean non-high-density lipoprotein...",Sex,Female,3.100000,NaN,2.700000,...,100,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN
1211,Afghanistan,2000,WHO Global Health Observatory,NCD_CHOL_MEANNONHDL_C,"Cholesterol, mean non-high-density lipoprotein...",Sex,Male,3.000000,NaN,2.700000,...,100,0,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN
1212,Afghanistan,2000,WHO Global Health Observatory,NCD_CHOL_MEANTOTALCHOL_A,"Cholesterol, mean total (age-standardized)",Sex,Female,4.300000,NaN,3.800000,...,100,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,total
1213,Afghanistan,2000,WHO Global Health Observatory,NCD_CHOL_MEANTOTALCHOL_A,"Cholesterol, mean total (age-standardized)",Sex,Male,4.200000,NaN,3.800000,...,100,0,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,total
1214,Afghanistan,2000,WHO Global Health Observatory,NCD_CHOL_MEANTOTALCHOL_C,"Cholesterol, mean total (crude)",Sex,Female,4.200000,NaN,3.800000,...,100,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN
1215,Afghanistan,2000,WHO Global Health Observatory,NCD_CHOL_MEANTOTALCHOL_C,"Cholesterol, mean total (crude)",Sex,Male,4.200000,NaN,3.800000,...,100,0,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN
1216,Afghanistan,2000,WHO Global Health Observatory,NCD_DIABETES_PREVALENCE_AGESTD_18,Diabetes prevalence (18+ years) (age-standardi...,Sex,Female,13.499095,NaN,6.351323,...,100,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN

Désormais, attaquons nous à la simplification de la distance pour obtenir une aide technique (assistive techology)

### Simplification des annotations de la distance pour obtenir une aide technique (assistive techology)

Pour "assistive technology", nous avons les catégories suivantes :
- Assistive technology: Travel distance to obtain assistive products (%) - 100+ km,
- Assistive technology: Travel distance to obtain assistive products (%) - 26-50 km,
- Assistive technology: Travel distance to obtain assistive products (%) - 51-100 km,
- Assistive technology: Travel distance to obtain assistive products (%) - 6-25 km,
- Assistive technology: Travel distance to obtain assistive products (%) - <6 km,
- Assistive technology: Met need of assistive products (%),
- Assistive technology: Need of assistive products (%),
- et enfin, Assistive technology: Use of assistive products (%)

Nous allons le renommer par les 6 catégories suivantes :
- near
- close
- mid_distance
- need
- use
- et enfin, coverage

In [36]:
def assistive_techno(x):
    if pd.isna(x):
        return np.nan
    
    if x in ["Assistive technology: Travel distance to obtain assistive products (%) - 100+ km",
             "Assistive technology: Travel distance to obtain assistive products (%) - 51-100 km"
            ]:
        return "near"
    
    if x in ["Assistive technology: Travel distance to obtain assistive products (%) - 26-50 km"]:
        return "mid_distance"
    
    if x in ["Assistive technology: Travel distance to obtain assistive products (%) - <6 km",
             "Assistive technology: Travel distance to obtain assistive products (%) - 6-25 km"]:
        return "close"

    if "Assistive technology: Need of assistive products (%)" in x:
        return "need"

    if "Assistive technology: Use of assistive products (%)" in x:
        return "use"

    if "Assistive technology: Met need of assistive products (%)" in x:
        return "met_need"
    
health_inequality["assistive_techno"] = health_inequality["indicator_name"].apply(assistive_techno)

In [37]:
health_inequality.iloc[599000:599010] # choix de ligne qui présente la catégorie "assitive technology" afin de vérifier si tout fonctionne

,country,date,source,indicator_abbr,indicator_name,dimension,group,value,se,ci_lower,...,ordered_dimension,subgroup_order,reference_subgroup,region,income_level,update,dataset_id,age,cholesterol,assistive_techno
613464,Pakistan,2019,WHO Global Health Observatory,ASSISTIVETECH_METNEED,Assistive technology: Met need of assistive pr...,Place of residence,Rural,3.05667,NaN,NaN,...,0,0,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,met_need
613465,Pakistan,2019,WHO Global Health Observatory,ASSISTIVETECH_METNEED,Assistive technology: Met need of assistive pr...,Place of residence,Urban,4.46807,NaN,NaN,...,0,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,met_need
613466,Pakistan,2019,WHO Global Health Observatory,ASSISTIVETECH_METNEED,Assistive technology: Met need of assistive pr...,Sex,Female,3.78582,NaN,NaN,...,0,0,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,met_need
613467,Pakistan,2019,WHO Global Health Observatory,ASSISTIVETECH_METNEED,Assistive technology: Met need of assistive pr...,Sex,Male,3.70680,NaN,NaN,...,0,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,met_need
613468,Pakistan,2019,WHO Global Health Observatory,ASSISTIVETECH_TOTALNEED,Assistive technology: Need of assistive produc...,Age (9 groups) (0-80+),0-4 years,2.23281,NaN,NaN,...,1,1,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,-25,NaN,need
613469,Pakistan,2019,WHO Global Health Observatory,ASSISTIVETECH_TOTALNEED,Assistive technology: Need of assistive produc...,Age (9 groups) (0-80+),18-29 years,8.58913,NaN,NaN,...,1,3,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,-60,NaN,need
613470,Pakistan,2019,WHO Global Health Observatory,ASSISTIVETECH_TOTALNEED,Assistive technology: Need of assistive produc...,Age (9 groups) (0-80+),30-39 years,14.52247,NaN,NaN,...,1,4,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,-60,NaN,need
613471,Pakistan,2019,WHO Global Health Observatory,ASSISTIVETECH_TOTALNEED,Assistive technology: Need of assistive produc...,Age (9 groups) (0-80+),40-49 years,28.71667,NaN,NaN,...,1,5,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,need
613472,Pakistan,2019,WHO Global Health Observatory,ASSISTIVETECH_TOTALNEED,Assistive technology: Need of assistive produc...,Age (9 groups) (0-80+),5-17 years,6.89762,NaN,NaN,...,1,2,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,-25,NaN,need
613473,Pakistan,2019,WHO Global Health Observatory,ASSISTIVETECH_TOTALNEED,Assistive technology: Need of assistive produc...,Age (9 groups) (0-80+),50-59 years,46.07066,NaN,NaN,...,1,6,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,-60,NaN,need

### Simplification des catégories sur le diabète

In [38]:
health_inequality.loc[
    health_inequality["indicator_name"].str.contains("Diabetes", na=False),
    "indicator_name"
].unique()

<StringArray>
[        'Diabetes prevalence (18+ years) (age-standardized) (%)',
         'Diabetes prevalence (30+ years) (age-standardized) (%)',
                    'Diabetes prevalence (18+ years) (crude) (%)',
                    'Diabetes prevalence (30+ years) (crude) (%)',
 'Diabetes treatment coverage (30+ years) (age-standardized) (%)',
            'Diabetes treatment coverage (30+ years) (crude) (%)']
Length: 6, dtype: str

In [39]:
def diabetes_simplification(x):
    if pd.isna(x):
        return np.nan

    x = x.lower()

    if "prevalence" in x:
        return "prevalence"

    if "treatment coverage" in x:
        return "treatment_coverage"

    return np.nan

health_inequality["diabetes"] = health_inequality["indicator_name"].apply(diabetes_simplification)

In [40]:
health_inequality[health_inequality["indicator_name"].str.contains("Diabetes", na=False)]

,country,date,source,indicator_abbr,indicator_name,dimension,group,value,se,ci_lower,...,subgroup_order,reference_subgroup,region,income_level,update,dataset_id,age,cholesterol,assistive_techno,diabetes
300,Afghanistan,1990,WHO Global Health Observatory,NCD_DIABETES_PREVALENCE_AGESTD_18,Diabetes prevalence (18+ years) (age-standardi...,Sex,Female,10.857809,NaN,4.358302,...,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,prevalence
301,Afghanistan,1990,WHO Global Health Observatory,NCD_DIABETES_PREVALENCE_AGESTD_18,Diabetes prevalence (18+ years) (age-standardi...,Sex,Male,10.218534,NaN,4.321409,...,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,prevalence
302,Afghanistan,1990,WHO Global Health Observatory,NCD_DIABETES_PREVALENCE_AGESTD_30,Diabetes prevalence (30+ years) (age-standardi...,Sex,Female,14.327924,NaN,5.884140,...,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,prevalence
303,Afghanistan,1990,WHO Global Health Observatory,NCD_DIABETES_PREVALENCE_AGESTD_30,Diabetes prevalence (30+ years) (age-standardi...,Sex,Male,13.442478,NaN,5.842932,...,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,prevalence
304,Afghanistan,1990,WHO Global Health Observatory,NCD_DIABETES_PREVALENCE_CRUDE_18,Diabetes prevalence (18+ years) (crude) (%),Sex,Female,8.090014,NaN,3.014825,...,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,prevalence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
917622,occupied Palestinian territory,2021,WHO Global Health Observatory,NCD_DIABETES_PREVALENCE_CRUDE_30,Diabetes prevalence (30+ years) (crude) (%),Sex,Male,20.297565,NaN,14.978254,...,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,prevalence
917623,occupied Palestinian territory,2021,WHO Global Health Observatory,NCD_DIABETES_TREATMENT_AGESTD,Diabetes treatment coverage (30+ years) (age-s...,Sex,Female,60.769677,NaN,48.574460,...,0,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,treatment_coverage
917624,occupied Palestinian territory,2021,WHO Global Health Observatory,NCD_DIABETES_TREATMENT_AGESTD,Diabetes treatment coverage (30+ years) (age-s...,Sex,Male,56.627333,NaN,43.974772,...,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,treatment_coverage
917625,occupied Palestinian territory,2021,WHO Global Health Observatory,NCD_DIABETES_TREATMENT_CRUDE,Diabetes treatment coverage (30+ years) (crude...,Sex,Female,58.511853,NaN,46.659133,...,0,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,treatment_coverage
917626,occupied Palestinian territory,2021,WHO Global Health Observatory,NCD_DIABETES_TREATMENT_CRUDE,Diabetes treatment coverage (30+ years) (crude...,Sex,Male,53.948539,NaN,41.701731,...,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,treatment_coverage

### Simplification des catégories sur l'hypertension

In [41]:
health_inequality.loc[
    health_inequality["indicator_name"].str.contains("Hypertension", na=False),
    "indicator_name"
].unique()

<StringArray>
[                   'Hypertension: raised blood pressure (SBP>=140 OR DBP>=90) among adults aged 30-79 (crude) (%)',
         'Hypertension: raised blood pressure (SBP>=140 OR DBP>=90) among adults aged 30-79 (age-standardized) (%)',
 'Hypertension effective treatment coverage among adults aged 30-79 years with hypertension (age-standardized) (%)',
            'Hypertension effective treatment coverage among adults aged 30-79 years with hypertension (crude) (%)',
                 'Hypertension diagnosis coverage among adults aged 30-79 with hypertension (age-standardized) (%)',
                            'Hypertension diagnosis coverage among adults aged 30-79 with hypertension (crude) (%)',
                                     'Hypertension prevalence among adults aged 30-79 years (age-standardized) (%)',
                                                'Hypertension prevalence among adults aged 30-79 years (crude) (%)',
                 'Hypertension treatment coverage among adults aged 30-79 with hypertension (age-standardized) (%)',
                            'Hypertension treatment coverage among adults aged 30-79 with hypertension (crude) (%)']
Length: 10, dtype: str

In [42]:
def hypertension_simplification(x):
    if pd.isna(x):
        return np.nan

    x = x.lower()

    if "prevalence" in x:
        return "prevalence"
    
    if "diagnosis coverage" in x:
        return "diagnosis"

    if "treatment coverage" in x and "effective" not in x:
        return "treatment"

    if "effective treatment" in x:
        return "effective_treatment"

    return np.nan
health_inequality["hypertension"] = health_inequality["indicator_name"].apply(hypertension_simplification)

In [43]:
health_inequality[health_inequality["indicator_name"].str.contains("Hypertension", na=False)]

,country,date,source,indicator_abbr,indicator_name,dimension,group,value,se,ci_lower,...,reference_subgroup,region,income_level,update,dataset_id,age,cholesterol,assistive_techno,diabetes,hypertension
252,Afghanistan,1990,WHO Global Health Observatory,BP_03,Hypertension: raised blood pressure (SBP>=140 ...,Sex,Female,31.914532,NaN,17.494072,...,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN
253,Afghanistan,1990,WHO Global Health Observatory,BP_03,Hypertension: raised blood pressure (SBP>=140 ...,Sex,Male,28.278271,NaN,15.091063,...,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN
254,Afghanistan,1990,WHO Global Health Observatory,BP_04,Hypertension: raised blood pressure (SBP>=140 ...,Sex,Female,36.247894,NaN,21.071648,...,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN
255,Afghanistan,1990,WHO Global Health Observatory,BP_04,Hypertension: raised blood pressure (SBP>=140 ...,Sex,Male,32.318203,NaN,18.506435,...,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN
312,Afghanistan,1990,WHO Global Health Observatory,NCD_HYP_CONTROL_A,Hypertension effective treatment coverage amon...,Sex,Female,3.900000,NaN,0.300000,...,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,treatment_coverage,effective_treatment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
917444,occupied Palestinian territory,2019,WHO Global Health Observatory,NCD_HYP_PREVALENCE_C,Hypertension prevalence among adults aged 30-7...,Sex,Male,35.700000,NaN,24.500000,...,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,prevalence,prevalence
917445,occupied Palestinian territory,2019,WHO Global Health Observatory,NCD_HYP_TREATMENT_A,Hypertension treatment coverage among adults a...,Sex,Female,50.700000,NaN,32.900000,...,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,treatment_coverage,treatment
917446,occupied Palestinian territory,2019,WHO Global Health Observatory,NCD_HYP_TREATMENT_A,Hypertension treatment coverage among adults a...,Sex,Male,47.100000,NaN,30.100000,...,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,treatment_coverage,treatment
917447,occupied Palestinian territory,2019,WHO Global Health Observatory,NCD_HYP_TREATMENT_C,Hypertension treatment coverage among adults a...,Sex,Female,47.100000,NaN,29.900000,...,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,treatment_coverage,treatment
917448,occupied Palestinian territory,2019,WHO Global Health Observatory,NCD_HYP_TREATMENT_C,Hypertension treatment coverage among adults a...,Sex,Male,42.100000,NaN,26.200000,...,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,treatment_coverage,treatment

### Simplification des catégories sur l'alcoolémie

Listons toutes les catégories existantes :

In [44]:
health_inequality.loc[
    health_inequality["indicator_name"].str.contains("Alcohol", na=False),
    "indicator_name"
].unique()

<StringArray>
[            'Alcohol, per capita consumption (15+ years, among drinkers only) (in litres of pure alcohol)',
                                                                         'Alcohol, abstainers lifetime (%)',
                                                                'Alcohol, abstainers in past 12 months (%)',
                                              'Alcohol, consumers in past 12 months (age-standardized) (%)',
                                                                             'Alcohol, former drinkers (%)',
 'Alcohol, heavy episodic drinking in past 30 days (15+ years, among drinkers only) (age-standardized) (%)',
                      'Alcohol, heavy episodic drinking in past 30 days (15+ years) (age-standardized) (%)',
                                                     'Alcohol, average daily intake among drinkers (grams)',
                                                'Alcohol, harmful use, 12 month prevalence (15+ years) (%)',
                                                        'Alcohol, current drinkers (youth 15-19 years) (%)',
                                 'Alcohol, heavy episodic drinking in past 30 days (youth 15-19 years) (%)',
            'Alcohol, heavy episodic drinking in past 30 days (youth 15-19 years, among drinkers only) (%)',
                                              'Alcohol-attributable liver cirrhosis deaths (15+ years) (%)',
                                                 'Alcohol-attributable road traffic deaths (15+ years) (%)',
                                                                'Alcohol-attributable all-cause deaths (%)',
                                          'Alcohol, heavy continuous drinkers in past year (15+ years) (%)',
                     'Alcohol, heavy continuous drinkers in past year (15+ years, among drinkers only) (%)',
                                  'Alcohol, heavy continuous drinkers in past year (youth 15-19 years) (%)',
             'Alcohol, heavy continuous drinkers in past year (youth 15-19 years, among drinkers only) (%)',
                                   'Alcohol-attributable DALYs (age-standardized) (per 100 000 population)']
Length: 20, dtype: str

In [45]:
def alcohol_simplification(x):
    if pd.isna(x):
        return np.nan

    x = x.lower()

    if "abstainers" in x or "non-drinker" in x:
        return "no_or_light"

    if "consumers" in x or "average daily intake" in x:
        return "moderate"

    if "heavy episodic" in x or "heavy continuous" in x:
        return "heavy"

    if "harmful" in x or "attributable" in x or "cirrhosis" in x or "road traffic" in x or "dalys" in x:
        return "alcoholism"

    return np.nan

health_inequality["alcohol"] = health_inequality["indicator_name"].apply(alcohol_simplification)

In [46]:
health_inequality[health_inequality["indicator_name"].str.contains("Alcohol", na=False)]

,country,date,source,indicator_abbr,indicator_name,dimension,group,value,se,ci_lower,...,region,income_level,update,dataset_id,age,cholesterol,assistive_techno,diabetes,hypertension,alcohol
1270,Afghanistan,2000,WHO Global Health Observatory,SA_0000001404,"Alcohol, per capita consumption (15+ years, am...",Sex,Female,0.059616,NaN,0.000000,...,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN,NaN
1271,Afghanistan,2000,WHO Global Health Observatory,SA_0000001404,"Alcohol, per capita consumption (15+ years, am...",Sex,Male,0.165099,NaN,0.000000,...,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN,NaN
1272,Afghanistan,2000,WHO Global Health Observatory,SA_0000001409,"Alcohol, abstainers lifetime (%)",Sex,Female,97.684674,NaN,97.331739,...,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN,no_or_light
1273,Afghanistan,2000,WHO Global Health Observatory,SA_0000001409,"Alcohol, abstainers lifetime (%)",Sex,Male,95.318629,NaN,94.603876,...,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN,no_or_light
1274,Afghanistan,2000,WHO Global Health Observatory,SA_0000001411,"Alcohol, abstainers in past 12 months (%)",Sex,Female,98.903319,NaN,98.510751,...,Eastern Mediterranean,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN,no_or_light
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
914169,Zimbabwe,2020,WHO Global Health Observatory,SA_0000001416,"Alcohol, heavy episodic drinking in past 30 da...",Sex,Male,53.568235,NaN,52.337767,...,African,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN,heavy
914170,Zimbabwe,2020,WHO Global Health Observatory,SA_0000001739,"Alcohol, heavy episodic drinking in past 30 da...",Sex,Female,4.477093,NaN,4.064800,...,African,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN,heavy
914171,Zimbabwe,2020,WHO Global Health Observatory,SA_0000001739,"Alcohol, heavy episodic drinking in past 30 da...",Sex,Male,14.701484,NaN,13.725821,...,African,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN,heavy
914172,Zimbabwe,2020,WHO Global Health Observatory,SA_0000001751,"Alcohol, average daily intake among drinkers (...",Sex,Female,14.968984,NaN,5.980256,...,African,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN,moderate
914173,Zimbabwe,2020,WHO Global Health Observatory,SA_0000001751,"Alcohol, average daily intake among drinkers (...",Sex,Male,38.716123,NaN,16.333455,...,African,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN,moderate

### Simplification des catégories sur le tabaggisme

Listons toutes les catégories existantes :

In [48]:
health_inequality.loc[
    health_inequality["indicator_name"].str.contains("Tobacco", na=False),
    "indicator_name"
].unique()

<StringArray>
[                  'Tobacco: current cigarette smoking prevalence (model-based estimates) (%)',
 'Tobacco, current cigarette smoking prevalence (model-based estimates, age-standardized) (%)',
                     'Tobacco, current tobacco smoking prevalence (model-based estimates) (%)',
   'Tobacco, current tobacco smoking prevalence (model-based estimates, age-standardized) (%)',
                         'Tobacco, current tobacco use prevalence (model-based estimates) (%)',
       'Tobacco, current tobacco use prevalence (model-based estimates, age-standardized) (%)',
           'Tobacco: current cigarette smoking among adolescents (survey-based estimates) (%)',
             'Tobacco, current e-cigarette use among adolescents (survey-based estimates) (%)',
       'Tobacco, current smokeless tobacco use among adolescents (survey-based estimates) (%)',
             'Tobacco, current tobacco smoking among adolescents (survey-based estimates) (%)',
                 'Tobacco, current tobacco use among adolescents (survey-based estimates) (%)',
             'Tobacco, daily cigarette smoking among adolescents (survey-based estimates) (%)',
               'Tobacco, daily tobacco smoking among adolescents (survey-based estimates) (%)',
                'Tobacco: current cigarette smoking among adults (survey-based estimates) (%)',
                  'Tobacco, current e-cigarette use among adults (survey-based estimates) (%)',
            'Tobacco, current smokeless tobacco use among adults (survey-based estimates) (%)',
                  'Tobacco, current tobacco smoking among adults (survey-based estimates) (%)',
                      'Tobacco, current tobacco use among adults (survey-based estimates) (%)',
                  'Tobacco, daily cigarette smoking among adults (survey-based estimates) (%)',
                    'Tobacco, daily e-cigarette use among adults (survey-based estimates) (%)',
              'Tobacco, daily smokeless tobacco use among adults (survey-based estimates) (%)',
                    'Tobacco, daily tobacco smoking among adults (survey-based estimates) (%)',
                        'Tobacco, daily tobacco use among adults (survey-based estimates) (%)']
Length: 23, dtype: str

In [49]:
def tobacco_simplification(x):
    if pd.isna(x):
        return np.nan

    x = x.lower()

    if "current tobacco use" in x and "daily" not in x and "smoking" not in x:
        return "non_smoker"

    if "current cigarette smoking" in x or "current smoking" in x:
        return "light_smoker"

    if "daily cigarette" in x or "daily tobacco smoking" in x:
        return "moderate_smoker"

    if "heavy" in x:
        return "heavy_smoker"

    return np.nan

health_inequality["tobacco"] = health_inequality["indicator_name"].apply(tobacco_simplification)

In [50]:
health_inequality[health_inequality["indicator_name"].str.contains("Tobacco", na=False)]

,country,date,source,indicator_abbr,indicator_name,dimension,group,value,se,ci_lower,...,income_level,update,dataset_id,age,cholesterol,assistive_techno,diabetes,hypertension,alcohol,tobacco
1162,Afghanistan,2000,WHO Global Health Observatory,M_Est_cig_curr,Tobacco: current cigarette smoking prevalence ...,Sex,Female,3.9,NaN,1.6,...,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,prevalence,prevalence,NaN,light_smoker
1163,Afghanistan,2000,WHO Global Health Observatory,M_Est_cig_curr,Tobacco: current cigarette smoking prevalence ...,Sex,Male,30.7,NaN,14.5,...,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,prevalence,prevalence,NaN,light_smoker
1164,Afghanistan,2000,WHO Global Health Observatory,M_Est_cig_curr_std,"Tobacco, current cigarette smoking prevalence ...",Sex,Female,4.2,NaN,1.9,...,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,prevalence,prevalence,NaN,light_smoker
1165,Afghanistan,2000,WHO Global Health Observatory,M_Est_cig_curr_std,"Tobacco, current cigarette smoking prevalence ...",Sex,Male,29.9,NaN,13.2,...,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,prevalence,prevalence,NaN,light_smoker
1166,Afghanistan,2000,WHO Global Health Observatory,M_Est_smk_curr,"Tobacco, current tobacco smoking prevalence (m...",Sex,Female,9.6,NaN,3.9,...,Low-income,17 October 2025,rep_gho,NaN,NaN,NaN,prevalence,prevalence,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
917152,occupied Palestinian territory,2016,WHO Global Health Observatory,Yth_curr_tob_use,"Tobacco, current tobacco use among adolescents...",Sex,Male,43.3,NaN,NaN,...,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN,NaN,non_smoker
917153,occupied Palestinian territory,2016,WHO Global Health Observatory,Yth_daily_cig_smoking,"Tobacco, daily cigarette smoking among adolesc...",Sex,Female,NaN,NaN,NaN,...,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN,NaN,moderate_smoker
917154,occupied Palestinian territory,2016,WHO Global Health Observatory,Yth_daily_cig_smoking,"Tobacco, daily cigarette smoking among adolesc...",Sex,Male,NaN,NaN,NaN,...,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN,NaN,moderate_smoker
917155,occupied Palestinian territory,2016,WHO Global Health Observatory,Yth_daily_tob_smoking,"Tobacco, daily tobacco smoking among adolescen...",Sex,Female,NaN,NaN,NaN,...,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN,NaN,moderate_smoker
917156,occupied Palestinian territory,2016,WHO Global Health Observatory,Yth_daily_tob_smoking,"Tobacco, daily tobacco smoking among adolescen...",Sex,Male,NaN,NaN,NaN,...,Lower-middle-income,17 October 2025,rep_gho,NaN,NaN,NaN,NaN,NaN,NaN,moderate_smoker

### Réordonner les colonnes

In [51]:
print(health_inequality.columns)

Index(['country', 'date', 'source', 'indicator_abbr', 'indicator_name',
       'dimension', 'group', 'value', 'se', 'ci_lower', 'ci_upper',
       'population', 'flag', 'setting_average', 'country_code',
       'favourable_indicator', 'indicator_scale', 'ordered_dimension',
       'subgroup_order', 'reference_subgroup', 'region', 'income_level',
       'update', 'dataset_id', 'age', 'cholesterol', 'assistive_techno',
       'diabetes', 'hypertension', 'alcohol', 'tobacco'],
      dtype='str')

In [52]:
health_inequality = health_inequality[[

    # lieux
    "country", "country_code", "region", "income_level",
    "date", "update", "dataset_id",

    # Indicateurs
    "indicator_abbr", "indicator_name", "indicator_scale",
    "favourable_indicator", "source",

    # Regroupements / catégories
    "dimension", "group", "subgroup_order", "reference_subgroup",
    "ordered_dimension", "population", "age",

    # Nouveaux "features"   "alcohol", "tobacco", "diabetes", "hypertension",
    "cholesterol", "assistive_techno",

    # Valeurs
    "value", "se", "ci_lower", "ci_upper",
    "setting_average", "flag"
]]

In [56]:
pd.set_option("display.max_columns", None)
health_inequality.head(5)

,country,country_code,region,income_level,date,update,dataset_id,indicator_abbr,indicator_name,indicator_scale,favourable_indicator,source,dimension,group,subgroup_order,reference_subgroup,ordered_dimension,population,age,cholesterol,assistive_techno,value,se,ci_lower,ci_upper,setting_average,flag
0,Afghanistan,AFG,Eastern Mediterranean,Low-income,1957,17 October 2025,rep_gho,MDG_0000000001,Infant mortality rate (deaths per 1000 live bi...,1000,0,WHO Global Health Observatory,Sex,Female,0,0,0,NaN,NaN,NaN,NaN,247.968162,NaN,194.625473,311.942868,260.942246,NaN
1,Afghanistan,AFG,Eastern Mediterranean,Low-income,1957,17 October 2025,rep_gho,MDG_0000000001,Infant mortality rate (deaths per 1000 live bi...,1000,0,WHO Global Health Observatory,Sex,Male,0,1,0,NaN,NaN,NaN,NaN,272.898981,NaN,214.032553,343.030365,260.942246,NaN
2,Afghanistan,AFG,Eastern Mediterranean,Low-income,1957,17 October 2025,rep_gho,MDG_0000000007,Under-five mortality rate (model-based estimat...,1000,0,WHO Global Health Observatory,Sex,Female,0,0,0,NaN,NaN,NaN,NaN,363.074361,NaN,286.019402,455.787860,371.323816,NaN
3,Afghanistan,AFG,Eastern Mediterranean,Low-income,1957,17 October 2025,rep_gho,MDG_0000000007,Under-five mortality rate (model-based estimat...,1000,0,WHO Global Health Observatory,Sex,Male,0,1,0,NaN,NaN,NaN,NaN,379.310303,NaN,297.924681,474.512216,371.323816,NaN
4,Afghanistan,AFG,Eastern Mediterranean,Low-income,1958,17 October 2025,rep_gho,MDG_0000000001,Infant mortality rate (deaths per 1000 live bi...,1000,0,WHO Global Health Observatory,Sex,Female,0,0,0,NaN,NaN,NaN,NaN,245.144576,NaN,197.317972,302.768372,257.763954,NaN